# Generated by Django 6.0 on 2026-05-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mentorship', 'Mentorship'), ('Internship', 'Internship'), ('Course', 'Course'), ('Fellowship', 'Fellowship'), ('Session', 'Session'), ('Online Course', 'Online Course')], help_text='The type of development program', max_length=50)),
                ('duration', models.CharField(help_text="Duration string (e.g., '2 months', '1 Day', '-')", max_length=30)),
                ('company', models.CharField(help_text='The organizing company or academy', max_length=100)),
                ('subject', models.CharField(help_text='The focus area or technical topic covered', max_length=200)),
                ('link', models.URLField(blank=True, help_text='Link to certificates, drives, or resources', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Professional Development',
                'verbose_name_plural': 'Professional Development Records',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project', max_length=100, unique=True)),
                ('project_note', models.CharField(help_text='A short tagline or subtitle detailing what the system does', max_length=255)),
                ('github_link', models.URLField(help_text='Direct link to the GitHub repository', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed overview and feature breakdown of the project', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this project record was first saved')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
