# Generated by Django 6.0 on 2026-05-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_note',
        ),
        migrations.AddField(
            model_name='professionaldevelopment',
            name='learnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professionaldevelopment',
            name='skills_acquired',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('group', 'Group'), ('academic', 'Academic'), ('open_source', 'Open Source')], default='solo', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=dict, help_text='Categorized object mapping arrays of languages, frameworks, and tools.'),
        ),
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='name',
            field=models.CharField(choices=[('Mentorship', 'Mentorship'), ('Internship', 'Internship'), ('Course', 'Course'), ('Fellowship', 'Fellowship'), ('Session', 'Session'), ('Online Course', 'Online Course')], max_length=50),
        ),
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
