# Generated by Django 6.0 on 2026-06-05 05:18

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_link_professionaldevelopment_certificate_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., Alex 'Wraith' Johnson", max_length=255, verbose_name='Operative Name / Codename')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Secure Email Protocol')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Encrypted Communication Line')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Base Location / Physical Address')),
                ('base_secret_code', models.CharField(help_text='e.g., 8888', max_length=4, verbose_name='Base Secret Code')),
                ('sidebar_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sidebar Sequential Code')),
                ('portal_dream', models.TextField(verbose_name='Dream / Vision for Secret Portal')),
                ('clearance_level', models.CharField(default='ALPHA-9', max_length=50, verbose_name='Clearance Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Transmission Timestamp')),
            ],
            options={
                'verbose_name': 'Personnel Profile',
                'verbose_name_plural': 'Personnel Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Chronological Stamp')),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Okay', 'Okay'), ('Neutral', 'Neutral'), ('Sad', 'Sad'), ('Wired', 'Wired'), ('Tired', 'Tired')], default='Neutral', max_length=15, verbose_name='Mood State')),
                ('title', models.CharField(max_length=255, verbose_name='Day Label / Objective Title')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='scrapbook/days/', verbose_name='Uploaded Local Asset')),
                ('remote_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Alternative Remote Image URL Fallback')),
                ('source', models.CharField(choices=[('local', 'Local'), ('remote', 'Remote')], default='remote', max_length=10, verbose_name='Active Image Subsystem Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='System Generation Ingestion Time')),
            ],
            options={
                'verbose_name': 'Daily Scrapbook Entry',
                'verbose_name_plural': 'Daily Scrapbook Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DreamWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, default='✨', help_text='A visual representation of the dream.', max_length=10)),
                ('wish', models.TextField(help_text='Description of the daydream or desired object.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dream Wish',
                'verbose_name_plural': 'Dream Wishes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HobbyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, default='✨', help_text='Unicode icon character or visual element label string.', max_length=12)),
                ('title', models.CharField(help_text='Clear label naming structural category e.g., Photography.', max_length=150)),
                ('text', models.TextField(help_text='Detailed analytical insight framing execution parameters or core personal metrics.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal Hobby Record',
                'verbose_name_plural': 'Personal Hobbies Registry Matrix',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MusicVibeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(help_text='The individual musician, group, or project entity name.', max_length=150)),
                ('track', models.CharField(help_text='The semantic title naming the tracking composition item.', max_length=200)),
                ('mood', models.CharField(help_text='Vibe description context e.g., 2am Deep-Focus Synth Loops.', max_length=255)),
                ('color', models.CharField(default='#10b981', help_text='Primary color design token hex code used for frontend background mix opacity calculations.', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color string (e.g., #6366f1).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Music Vibe Track',
                'verbose_name_plural': 'Music Vibes Playlist Matrix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperativeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, default='🎯', help_text='A visual representation of the dream/vision.', max_length=10, verbose_name='goal emoji visual identifier')),
                ('title', models.CharField(help_text='What are you building or working toward?', max_length=255, verbose_name='objective description title')),
                ('timeline', models.CharField(help_text='e.g. Q4 2026 / Ongoing / master system design 2025', max_length=100, verbose_name='projected chronological timeframe')),
                ('done', models.BooleanField(default=False, help_text='Ticks the goal item if finalized.', verbose_name='completion status flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='system generation ingestion time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='matrix mutation timeline conversion')),
            ],
            options={
                'verbose_name': 'living list data flow goal',
                'verbose_name_plural': 'working toward goals pipeline Matrix',
                'ordering': ['done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperativeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, default='📝', help_text='Visual identifier for quick model convergence.', max_length=10, verbose_name='thought node emoji')),
                ('title', models.CharField(help_text='Decoupled from enterprise mechanics.', max_length=255, verbose_name='note subject title')),
                ('text', models.TextField(help_text='Vectorized narrative structure. Keep it decoupled.', verbose_name='internal thought stream')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data Matrix insertion time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='matrix matrix mutation time')),
            ],
            options={
                'verbose_name': 'operative private thought',
                'verbose_name_plural': 'operative thoughts Matrix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapbookStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Memory Label')),
                ('image', models.ImageField(upload_to=api.models.scrapbook_upload_path, verbose_name='Archived Image')),
                ('remote_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(choices=[('local', 'Local Upload'), ('remote', 'Remote URL')], default='local', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scrapbook Stamp',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('drama', 'Drama'), ('movie', 'Movie'), ('anime', 'Anime')], default='drama', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('Slice of Life', 'Slice of Life'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Action', 'Action'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Crime/Dark Comedy', 'Crime/Dark Comedy'), ('Romance/Fantasy', 'Romance/Fantasy'), ('Horror/Action', 'Horror/Action'), ('Action/Superhero', 'Action/Superhero'), ('Action/Dark', 'Action/Dark'), ('Romance/Music', 'Romance/Music'), ('Drama/Fantasy', 'Drama/Fantasy'), ('Adventure/Fantasy', 'Adventure/Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Comedy', 'Comedy')], max_length=50)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)])),
                ('episodes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('Watching', 'Watching'), ('Finished', 'Finished'), ('Plan to Watch', 'Plan to Watch'), ('On Hold', 'On Hold'), ('Dropped', 'Dropped')], default='Plan to Watch', max_length=20)),
                ('emoji', models.CharField(default='🎬', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
