# Generated by Django 6.0 on 2026-06-05 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aboutme_daylog_dreamwish_hobbyitem_musicvibeitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='daylog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dreamwish',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='hobbyitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='musicvibeitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='operativegoal',
            options={'ordering': ['done', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='operativenote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='professionaldevelopment',
            options={'verbose_name': 'Professional Development'},
        ),
        migrations.AlterModelOptions(
            name='scrapbookstamp',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='daylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='scrapbook/days/'),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Okay', 'Okay'), ('Neutral', 'Neutral'), ('Sad', 'Sad'), ('Wired', 'Wired'), ('Tired', 'Tired')], default='Neutral', max_length=15),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='remote_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('remote', 'Remote')], default='remote', max_length=10),
        ),
        migrations.AlterField(
            model_name='daylog',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='musicvibeitem',
            name='artist',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='musicvibeitem',
            name='color',
            field=models.CharField(default='#10b981', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color string (e.g., #6366f1).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='musicvibeitem',
            name='mood',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='musicvibeitem',
            name='track',
            field=models.CharField(max_length=200),
        ),
    ]
