# Generated by Django 6.0 on 2026-06-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_alter_aboutme_options_alter_daylog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaldevelopment',
            name='certificate_link',
        ),
        migrations.AddField(
            model_name='professionaldevelopment',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
