# Generated by Django 6.0 on 2026-06-12 09:39

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_professionaldevelopment_certificate_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='base_secret_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='clearance_level',
            field=models.CharField(default='ALPHA-9', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='portal_dream',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='sidebar_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dreamwish',
            name='emoji',
            field=models.CharField(blank=True, default='✨', max_length=10),
        ),
        migrations.AlterField(
            model_name='dreamwish',
            name='wish',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hobbyitem',
            name='emoji',
            field=models.CharField(blank=True, default='✨', max_length=12),
        ),
        migrations.AlterField(
            model_name='hobbyitem',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hobbyitem',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='musicvibeitem',
            name='color',
            field=models.CharField(default='#10b981', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='operativegoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='operativegoal',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operativegoal',
            name='emoji',
            field=models.CharField(blank=True, default='🎯', max_length=10),
        ),
        migrations.AlterField(
            model_name='operativegoal',
            name='timeline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operativegoal',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='operativegoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='operativenote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='operativenote',
            name='emoji',
            field=models.CharField(blank=True, default='📝', max_length=10),
        ),
        migrations.AlterField(
            model_name='operativenote',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='operativenote',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='operativenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='professionaldevelopment',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scrapbookstamp',
            name='image',
            field=models.ImageField(upload_to=api.models.scrapbook_upload_path),
        ),
    ]
