# Generated by Django 6.0 on 2026-07-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_project_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operativegoal",
            name="emoji",
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="emoji",
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="episodes",
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="note",
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="year",
        ),
        migrations.AlterField(
            model_name="operativegoal",
            name="timeline",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Thriller", "Thriller"),
                    ("Romance", "Romance"),
                    ("Action", "Action"),
                    ("Drama", "Drama"),
                    ("Fantasy", "Fantasy"),
                    ("BL", "BL"),
                    ("Horror", "Horror"),
                    ("Historical", "Historical"),
                    ("Crime/Dark Comedy", "Crime/Dark Comedy"),
                    ("Romance/Fantasy", "Romance/Fantasy"),
                    ("Horror/Action", "Horror/Action"),
                    ("Action/Superhero", "Action/Superhero"),
                    ("Action/Dark", "Action/Dark"),
                    ("Romance/Music", "Romance/Music"),
                    ("Drama/Fantasy", "Drama/Fantasy"),
                    ("Adventure/Fantasy", "Adventure/Fantasy"),
                    ("Sci-Fi", "Sci-Fi"),
                    ("Comedy", "Comedy"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Watching", "Watching"),
                    ("Completed", "Completed"),
                    ("Plan to Watch", "Plan to Watch"),
                    ("On Hold", "On Hold"),
                    ("Dropped", "Dropped"),
                ],
                default="Plan to Watch",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("drama", "Drama"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("book", "Book"),
                    ("manga", "Manga"),
                ],
                default="drama",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="GoalDayStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("done", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_statuses",
                        to="api.operativegoal",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
                "unique_together": {("goal", "day_number")},
            },
        ),
    ]
