# Generated by Django 6.0 on 2026-08-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_aboutme_clearance_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="live_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="genre",
            field=models.CharField(
                choices=[
                    ("BL", "BL"),
                    ("Bromance", "bromance"),
                    ("Detective", "detective"),
                    ("Historical", "historical"),
                    ("Thriller", "Thriller"),
                    ("Romance", "Romance"),
                    ("Action", "Action"),
                    ("Drama", "Drama"),
                    ("Fantasy", "Fantasy"),
                    ("Horror", "Horror"),
                    ("Sci-Fi", "Sci-Fi"),
                    ("Comedy", "Comedy"),
                    ("Crime", "crime"),
                    ("Adventure", "adventure"),
                    ("Sad", "sad"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Watching", "Watching"),
                    ("Completed", "Completed"),
                    ("Plan to Watch", "Plan to Watch"),
                    ("On Hold", "On Hold"),
                    ("Dropped", "Dropped"),
                    ("Faded", "faded"),
                ],
                default="Plan to Watch",
                max_length=20,
            ),
        ),
    ]
