# Generated by Django 6.0 on 2026-08-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_challenge_challengeday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="user",
        ),
    ]
